Vagrant.configure("2") do |config|
  config.vm.hostname = "gatling"
  config.vm.box = "precise64"
  config.omnibus.chef_version = :latest
  config.vm.network :private_network, ip: "33.33.33.10"
  config.vm.boot_timeout = 120
  config.berkshelf.enabled = true

  config.vm.provision :chef_solo do |chef|
    chef.run_list = []
  end
end
